### ISSUE TITLE
Hi, problem with menu

### ISSUE THREAD

**Issue by dyanakiev** [TryGhost/Blog#12]
When i open blog.ghost.org on my smartphone i cant open menu or on browser with zoom?

Thanks.

**Comment by TheEVIL** [comment]
Still not fixed :(

**Comment by ErisDS** [comment]
@7h3ev1l Can you please provide some details? Which phone and browser are you using? Which menu isn't working? What happens exactly?

**Comment by 7h3ev1l** [comment]
![screen shot 2016-01-16 at 15 56 12](https://cloud.githubusercontent.com/assets/11967079/12372720/b2af2b7e-bc69-11e5-909a-5a6022a1b6ed.png)
When i zoom in safari, responsive menu just not work..
This happen to in windows phone with microsoft edge.
