### ISSUE TITLE
Include application.css

### ISSUE THREAD

**Issue by PabloC** [TryGhost/Blog#15]
Would be great if the theme includes "https://ghost.org/assets/application.css".
At the moment seems to be part of ghost.org

**Comment by kevinansfield** [comment]
That file is only meant for styles used in the ghost.org application, not the blog which uses `screen.css`. Have you found something in there that is needed for the blog to display correctly?

**Comment by PabloC** [comment]
Hi,
The blog is linking this asset.

**Comment by JohnONolan** [comment]
Hi Pablo, 

This is intended - and not a bug. Thanks for keeping an eye out :)
