### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by paranoid-android** [TryGhost/Blog#18]
Hello,

I am interested in using the Ghost Blog theme. I noticed that it has an MIT license associated with it. However, I also noticed that it references [this line](https://github.com/TryGhost/Blog/blob/master/default.hbs#L19) references [this style sheet](https://ghost.org/assets/application-b28ae7a39daa8bb1cafe1e9aa145df74.css). However, that stylesheet doesn't have an MIT license with it as far as I can tell.

Is that stylesheet available somewhere? If so, where does it come from? Is it also MIT licensed? I'd really like to get that stylesheet and hack on it in my project. But, I want to do everything on the up-and-up and respect the Ghost licensing.

**Comment by JohnONolan** [comment]
That stylesheet is part of Ghost.org and - at present - is not open source licensed. I will say that we do have plans to change this in future.
