### ISSUE TITLE
Applied theme to personal blog but style is not applying.

### ISSUE THREAD

**Issue by rdtechie** [TryGhost/Blog#26]
So, I love the way you setup the blog on blog.ghost.io and I was very pleased to found out you host the code here. I'm just starting out with theming, and I wanted to use the ghost.io blog theme as a starting point. But I'm confused. I uploaded the code from here to my blog, hosted at ghost.io, but the style is not applying. Only partially (the navigation bar is visible). Is there something missing? Can you give some hints/tips on how to use this theme? Check my blog here: https://richarddiphoorn.ghost.io

**Comment by ErisDS** [comment]
@rdtechie I'm not exactly sure what you're asking here. If you could perhaps post some screenshots and more information I'm sure we could point you in the right direction.

Closing for now as it seems you already changed theme.

**Comment by rdtechie** [comment]
I've changed the theme back, so you can see. I would like to have my blog look like the Ghost.io's blog, but it looks like the theme is not applying completely. I just downloaded the code from this repo and uploaded it to my Ghost account and made it active.

**Comment by kevinansfield** [comment]
@rdtechie this theme isn't designed to be usable out of the box for any blog - it's customised for Ghost.org and will pull scripts etc from there to build navigation elements so won't work if you just download/upload to your own blog.

I would suggest looking in your web inspector console to see if you have any errors, you may be able to get a bit further by stripping out any script tags etc that are fetching from ghost.org domains.

Note that we've made this theme open source purely as an example and to be open, *not* to be a packaged/reusable theme so your mileage will vary trying to use and adapt it for your own purposes.

**Comment by rdtechie** [comment]
Understood @kevinansfield . Thanks for explanation.
