### ISSUE TITLE
Reduce posts per page

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Blog#29]
`blog.ghost.org` loads **25** posts per page. This results in loading > 20 images on page visit.

Outcome of  https://github.com/TryGhost/Team/issues/38.

> Parallelize downloads across hostnames

![lalallaa](https://user-images.githubusercontent.com/1160712/34882728-c432edfa-f7b7-11e7-810a-311ab8707723.png)

This warning is showing, because pingdom does not support http/2. And this warning is no longer valid with http/2 because of multiplexing. Even though the requests on page visit could be improved. We might want to increase our grade?

We could reduce posts per page to increase A initial loading time and B make the public grade performance better. Worth a try?

**Comment by JohnONolan** [comment]
25 posts per page is the Casper default - it's not a weird custom value - it's required to make the grid-design work / and for infinite scroll to be usable?

I don't think a viable strategy to improving loading performance is to just not-load-content-at-all?

**Comment by kirrg001** [comment]
> I don't think a viable strategy to improving loading performance is to just not-load-content-at-all?

It's not a strategy to improve loading performance. 

> This warning is showing, because pingdom does not support http/2. And this warning is no longer valid with http/2 because of multiplexing. Even though the requests on page visit could be improved. We might want to increase our grade?

Pingdom is out of date and doesn't support http/2. blog.ghost.org is [loaded over http/2](https://tools.keycdn.com/http2-test). Take a look at this [test tool](https://www.webpagetest.org/performance_optimization.php?test=180115_3G_c0bff024192dc90429c91414dd91ace1&run=2#cache_static_content), this result doesn't show the same warning and also shows that all images are loaded in parallel.

[From](https://kinsta.com/knowledgebase/parallelize-downloads-across-hostnames/):

> Note: If you are running over HTTPS with a provider that supports HTTP/2, this warning can usually be safely ignored now. With HTTP/2 multiple resources can now be loaded in parallel over a single connection.

Another [reference](https://forum.webflow.com/t/parallelize-downloads-across-hostnames/34242/9).

---

> We could reduce posts per page to increase A initial loading time and B make the public grade performance better. Worth a try?

My intention here was just to make the public grade better **for pingdom**, because people might use this tool a lot and it's showing a wrong grade. Furthermore i thought 25 posts are a lot, but if that is required for the grid, we can close this issue 👍

**Comment by JohnONolan** [comment]
If Pingdom test is out of date then it's safe to ignore this
