### ISSUE TITLE
Compress images

### ISSUE THREAD

**Issue by kirrg001** [TryGhost/Blog#30]
We uploaded images on https://blog.ghost.org which are not compressed good enough. Page load is 7.3 MB. Right now there is no image compression/resizing functionality in Ghost available - so this is always up to the blog owner - in this case it's us. Outcome of [this issue](https://github.com/TryGhost/Team/issues/38).

Example:

- https://blog.ghost.org/content/images/2017/07/DJI_0006-Edit.jpg 1,2mb

- [ ] decompress (or resize) images on blog.ghost.org

**Comment by kirrg001** [comment]
Which quality loss do we accept? Not sure what's Ghost's best practise here.

If you want to i can send you all the bigger images, you decompress/resize and i'll replace them on the server.

@JohnONolan

**Comment by JohnONolan** [comment]
The images on blog.ghost.org are already compressed to the maximum acceptable rate - the standard is to use tinypng.com. 

Again, https://github.com/TryGhost/Team/issues/38 is supposed to be focused around optimising *ghost* issues, not around what people can do to speed up a site by changing their content to use less-posts or smaller-images

**Comment by kirrg001** [comment]
> Again, TryGhost/Team#38 is supposed to be focused around 

#30 and #29 where just *side discoveries* while researching the ghost/ghost(pro) performance. It's absolutely okay to close them with a simple "Compression is at a maximum already and 25 posts is required for our grid-design to work".

**Comment by AileenCGN** [comment]
> "Compression is at a maximum already and 25 posts is required for our grid-design to work"
