### ISSUE TITLE
Theme is different then image

### ISSUE THREAD

**Issue by Cavain** [TryGhost/Blog#32]
Hello,

I just tried all of your releases but didn't found this theme which is showing in your blog theme image. 
https://cloud.githubusercontent.com/assets/120485/8188178/20c05762-144c-11e5-9ae2-dee093b617c0.png

**Comment by AileenCGN** [comment]
This was done with additional code injection for the different blogs. It would be version 2.0 or 1.0 tho.

> It's not intended for distribution as an easily re-usable theme, but it is provided here as open source for anybody to hack on and work with if they'd like to.

The image is also out of date and needs to be updated. Thanks for the indirect reminder 😉 

If you have any questions, please use our [forum](https://forum.ghost.org/) - https://forum.ghost.org, if you're not able to find the answer in our [documentation](https://docs.ghost.org/) - https://docs.ghost.org, as we're keeping GitHub issues only open for bugs.
