### ISSUE TITLE
SASS files need to declare charset

### ISSUE THREAD

**Issue by jahnreektor** [TryGhost/Blog#4]
When running sass, I came across the following error from the screen.scss file:

    Invalid US-ASCII character "\xE2"

The resolution to this issue was to declare the charset at the top as UTF-8:

    @charset "UTF-8";

After that, sass worked great.

Additional note: my sass version was out of date, at 3.1.x.  I had to upgrade to 3.4.x in order to compile correctly.

Thanks to the Ghost team for making this theme and the Ghost blog open source!

**Comment by verpixelt** [comment]
I think that should clarify things:
`When running on Ruby 1.9 and later, Sass is aware of the character encoding of documents.` and
`Sass will always encode its output as UTF-8. It will include a @charset declaration if and only if the output file contains non-ASCII characters. In compressed mode, a UTF-8 byte order mark is used in place of a @charset declaration.`
(source: http://sass-lang.com/documentation/file.SASS_REFERENCE.html)

**Comment by JohnONolan** [comment]
Thanks for the report!
