### ISSUE TITLE
This theme has a footer but we can never see it with the autoloading on scroll

### ISSUE THREAD

**Issue by mansona** [TryGhost/Blog#40]
Howdy folks 👋 

I just noticed that https://blog.ghost.org/ has a footer that is impossible to see because when you scroll to the bottom of the page it auto loads more articles and the footer disappears to infinity 🤔 

I don't really know what the solution might be here but I thought I should bring it up at least

**Comment by kevinansfield** [comment]
Hey 👋 The footer is usable on individual posts/pages, it's not expected to be reachable on index pages unless you've scrolled to the bottom of the infinite scroll.
